import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { formatDate, formatDateTime, formatKES, monthLabel } from "@kodi/shared";
import { supabase } from "../lib/supabase";
import { Loading, ErrorBanner } from "../components/ui";
import { Money } from "../components/domain";
import type { DepositSettlement, InvoiceWithRefs, PaymentWithRefs, Tenant } from "../lib/types";

interface DocOrg {
  name: string;
}

function DocShell({ orgName, title, children }: { orgName: string; title: string; children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-slate-200 py-8 print:bg-white print:py-0">
      <div className="no-print mx-auto mb-4 max-w-[210mm] text-right">
        <button
          onClick={() => window.print()}
          className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
        >
          Print / Save PDF
        </button>
      </div>
      <div className="print-doc mx-auto max-w-[210mm] rounded-lg border border-slate-300 bg-white p-10 shadow">
        <div className="border-b-2 border-slate-900 pb-4">
          <h1 className="text-2xl font-bold">{orgName}</h1>
          <p className="text-sm text-slate-500">Rent management · Kenya</p>
        </div>
        <h2 className="mt-4 text-xl font-bold">{title}</h2>
        {children}
        <div className="mt-8 border-t border-slate-200 pt-3 text-xs text-slate-400">
          Generated by Kodi rent manager · {formatDateTime(new Date())}
        </div>
      </div>
    </div>
  );
}

function Table({ head, rows }: { head: string[]; rows: React.ReactNode[][] }) {
  return (
    <table className="mt-3 w-full text-sm">
      <thead>
        <tr className="border-b border-slate-300 text-left text-xs uppercase text-slate-500">
          {head.map((h) => (
            <th key={h} className="py-2 pr-3">{h}</th>
          ))}
        </tr>
      </thead>
      <tbody className="divide-y divide-slate-100">
        {rows.map((r, i) => (
          <tr key={i}>
            {r.map((c, j) => (
              <td key={j} className="py-2 pr-3">{c}</td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

async function fetchOrgName(orgId: string): Promise<string> {
  const { data } = await supabase.from("orgs").select("name").eq("id", orgId).maybeSingle();
  return ((data as DocOrg | null)?.name) ?? "Kodi";
}

// ---------------------------------------------------------------------------
// Invoice
// ---------------------------------------------------------------------------
export function InvoiceDocPage() {
  const { id } = useParams<{ id: string }>();
  const [inv, setInv] = useState<(InvoiceWithRefs & { tenant: (Tenant & { unit_label?: string }) | null }) | null>(null);
  const [orgName, setOrgName] = useState("Kodi");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    supabase
      .from("invoices")
      .select("*, tenant:tenants(*), unit:units(label)")
      .eq("id", id)
      .maybeSingle()
      .then(async ({ data, error: e }) => {
        if (e) setError(e.message);
        else if (!data) setError("Invoice not found.");
        else {
          setInv(data as typeof inv);
          setOrgName(await fetchOrgName((data as { org_id: string }).org_id));
        }
      });
  }, [id]);

  if (error) return <div className="p-10"><ErrorBanner message={error} /></div>;
  if (!inv) return <div className="p-10"><Loading label="Loading invoice…" /></div>;

  return (
    <DocShell orgName={orgName} title={`Rent invoice — ${monthLabel(inv.month)}`}>
      <div className="mt-3 grid grid-cols-2 gap-4 text-sm">
        <div>
          <p className="text-slate-500">Billed to</p>
          <p className="font-semibold">{inv.tenant?.full_name}</p>
          <p>{inv.tenant?.phone}</p>
        </div>
        <div className="text-right">
          <p className="text-slate-500">Unit {(inv as { unit?: { label?: string } }).unit?.label ?? ""} · Due {formatDate(inv.due_date)}</p>
          <p>Status: <strong>{inv.status}</strong></p>
        </div>
      </div>
      <Table
        head={["Item", "Amount"]}
        rows={[
          ["Rent", <Money key="r" value={inv.lines.rent} />],
          ["Water", <Money key="w" value={inv.lines.water} />],
          ["Garbage", <Money key="g" value={inv.lines.garbage} />],
          ...(inv.lines.other > 0 ? [["Other", <Money key="o" value={inv.lines.other} />] as React.ReactNode[]] : []),
          [<strong key="t">Total</strong>, <Money key="tv" value={inv.total} className="font-bold" />],
          ["Paid", <Money key="p" value={inv.total - inv.balance} />],
          [<strong key="b">Balance due</strong>, <Money key="bv" value={inv.balance} className="font-bold" />],
        ]}
      />
      <p className="mt-4 text-sm text-slate-600">
        Please pay {formatKES(inv.balance)} on or before {formatDate(inv.due_date)} via M-Pesa to avoid late penalties.
      </p>
    </DocShell>
  );
}

// ---------------------------------------------------------------------------
// Receipt
// ---------------------------------------------------------------------------
export function ReceiptDocPage() {
  const { id } = useParams<{ id: string }>();
  const [pay, setPay] = useState<(PaymentWithRefs & { org_id: string }) | null>(null);
  const [orgName, setOrgName] = useState("Kodi");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    supabase
      .from("payments")
      .select("*, tenant:tenants(*)")
      .eq("id", id)
      .maybeSingle()
      .then(async ({ data, error: e }) => {
        if (e) setError(e.message);
        else if (!data) setError("Receipt not found.");
        else {
          setPay(data as typeof pay);
          setOrgName(await fetchOrgName((data as { org_id: string }).org_id));
        }
      });
  }, [id]);

  if (error) return <div className="p-10"><ErrorBanner message={error} /></div>;
  if (!pay) return <div className="p-10"><Loading label="Loading receipt…" /></div>;

  return (
    <DocShell orgName={orgName} title={`Payment receipt ${pay.receipt_no}`}>
      <div className="mt-3 grid grid-cols-2 gap-4 text-sm">
        <div>
          <p className="text-slate-500">Received from</p>
          <p className="font-semibold">{pay.tenant?.full_name}</p>
          <p>{(pay.tenant as Tenant | null)?.phone}</p>
        </div>
        <div className="text-right">
          <p className="text-slate-500">Date</p>
          <p className="font-semibold">{formatDateTime(pay.paid_at)}</p>
          <p>Method: {pay.method}{pay.mpesa_code ? ` · ${pay.mpesa_code}` : ""}</p>
        </div>
      </div>
      <Table
        head={["Description", "Amount"]}
        rows={[
          ["Rent payment", <Money key="a" value={pay.amount} />],
          [<strong key="t">Total received</strong>, <Money key="tv" value={pay.amount} className="font-bold" />],
        ]}
      />
      {pay.allocations.length > 0 && (
        <>
          <p className="mt-3 text-sm text-slate-500">Applied to:</p>
          <Table
            head={["Invoice", "Amount applied"]}
            rows={pay.allocations.map((a, i) => [
              <span key={`i${i}`}>Invoice</span>,
              <Money key={`a${i}`} value={a.amount} />,
            ])}
          />
        </>
      )}
      {pay.note && <p className="mt-3 text-sm text-slate-600">Note: {pay.note}</p>}
    </DocShell>
  );
}

// ---------------------------------------------------------------------------
// Tenant statement
// ---------------------------------------------------------------------------
export function StatementDocPage() {
  const { tenantId } = useParams<{ tenantId: string }>();
  const [tenant, setTenant] = useState<Tenant | null>(null);
  const [invoices, setInvoices] = useState<InvoiceWithRefs[]>([]);
  const [payments, setPayments] = useState<PaymentWithRefs[]>([]);
  const [orgName, setOrgName] = useState("Kodi");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!tenantId) return;
    (async () => {
      const t = await supabase.from("tenants").select("*").eq("id", tenantId).maybeSingle();
      if (t.error) { setError(t.error.message); return; }
      if (!t.data) { setError("Tenant not found."); return; }
      setTenant(t.data as Tenant);
      setOrgName(await fetchOrgName((t.data as Tenant).org_id));
      const inv = await supabase.from("invoices").select("*").eq("tenant_id", tenantId).order("month");
      const pay = await supabase.from("payments").select("*").eq("tenant_id", tenantId).order("paid_at");
      if (inv.error) setError(inv.error.message);
      else setInvoices((inv.data ?? []) as InvoiceWithRefs[]);
      if (pay.error) setError(pay.error.message);
      else setPayments((pay.data ?? []) as PaymentWithRefs[]);
    })();
  }, [tenantId]);

  if (error) return <div className="p-10"><ErrorBanner message={error} /></div>;
  if (!tenant) return <div className="p-10"><Loading label="Loading statement…" /></div>;

  const balance = invoices.reduce((s, i) => s + i.balance, 0);

  return (
    <DocShell orgName={orgName} title={`Tenant statement — ${tenant.full_name}`}>
      <p className="mt-3 text-sm text-slate-600">
        {tenant.phone} · Deposit held: <Money value={tenant.deposit_held} /> · Current balance:{" "}
        <Money value={balance} className="font-bold" />
      </p>
      <h3 className="mt-4 font-semibold">Invoices</h3>
      <Table
        head={["Month", "Total", "Paid", "Balance"]}
        rows={invoices.map((i) => [
          monthLabel(i.month),
          <Money key="t" value={i.total} />,
          <Money key="p" value={i.total - i.balance} />,
          <Money key="b" value={i.balance} />,
        ])}
      />
      <h3 className="mt-4 font-semibold">Payments</h3>
      <Table
        head={["Date", "Receipt", "Method", "Amount"]}
        rows={payments.map((p) => [
          formatDate(p.paid_at),
          p.receipt_no,
          p.mpesa_code ? `M-Pesa ${p.mpesa_code}` : p.method,
          <Money key="a" value={p.amount} />,
        ])}
      />
    </DocShell>
  );
}

// ---------------------------------------------------------------------------
// Deposit settlement
// ---------------------------------------------------------------------------
export function SettlementDocPage() {
  const { id } = useParams<{ id: string }>();
  const [s, setS] = useState<(DepositSettlement & { tenant?: Tenant | null }) | null>(null);
  const [orgName, setOrgName] = useState("Kodi");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    supabase
      .from("deposit_settlements")
      .select("*, tenant:tenants(*)")
      .eq("id", id)
      .maybeSingle()
      .then(async ({ data, error: e }) => {
        if (e) setError(e.message);
        else if (!data) setError("Settlement not found.");
        else {
          setS(data as typeof s);
          setOrgName(await fetchOrgName((data as { org_id: string }).org_id));
        }
      });
  }, [id]);

  if (error) return <div className="p-10"><ErrorBanner message={error} /></div>;
  if (!s) return <div className="p-10"><Loading label="Loading settlement…" /></div>;

  return (
    <DocShell orgName={orgName} title="Deposit settlement">
      <p className="mt-3 text-sm text-slate-600">
        Tenant: <strong>{s.tenant?.full_name}</strong> · Deposit held: <Money value={s.deposit_held} />
      </p>
      <Table
        head={["Deduction", "Amount"]}
        rows={[
          ...s.deductions.map((d, i) => [d.label, <Money key={i} value={d.amount} />]),
          [<strong key="t">Total deductions</strong>, <Money key="tv" value={s.total_deductions} className="font-bold" />],
          [<strong key="r">Refund to tenant</strong>, <Money key="rv" value={s.refund_amount} className="font-bold" />],
        ]}
      />
      {s.notes && <p className="mt-3 text-sm text-slate-600">Notes: {s.notes}</p>}
      <div className="mt-10 grid grid-cols-2 gap-8 text-sm">
        <div className="border-t border-slate-400 pt-2">Landlord signature & date</div>
        <div className="border-t border-slate-400 pt-2">Tenant signature & date</div>
      </div>
    </DocShell>
  );
}
